version: '3'
services:
  flask-ml:
    container_name: flask-ml
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: flask-ml
    env_file:
      - ./docker/.env
    restart: always
    ports:
      - "33333:5000"
