version: '3'
services:
  flask-ml:
    container_name: flask-ml
    build:
      context: .
      dockerfile: ./docker/Dockerfile-production
    image: flask-ml
    env_file:
      - ./docker/production.env
    restart: always
    ports:
      - "3333:5000"
